=== Frostyezz/docker-xml/flori.dtd
<!ELEMENT flori (floare+)>
<!ELEMENT floare (nume, culoare, marime, pret)>
<!ELEMENT nume (#PCDATA)>
<!ELEMENT culoare (#PCDATA)>
<!ELEMENT marime (#PCDATA)>
<!ELEMENT pret (#PCDATA)>

=== Frostyezz/docker-xml/flori.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flori SYSTEM "flori.dtd">
<flori><floare><nume>trandafiri</nume><culoare>mov</culoare><marime>medii</marime><pret>80</pret></floare><floare><nume>lalele</nume><culoare>mov</culoare><marime>medii</marime><pret>80</pret></floare><floare><nume>lalele</nume><culoare>mov</culoare><marime>medii</marime><pret>80</pret></floare></flori>
